---
functional:
  - Пользователь должен иметь возможность регистрации нового аккаунта, в том числе через Github и Discord
  - Пользователь должен иметь возможность войти в собственный аккаунт и выйти из него
  - Должна быть функция восстанонавления пароля
  - Пользователь должен иметь возможность просматривать свой профиль и редактировать информацию о себе
  - Пользователь должен иметь возможность просматривать чужие соревнования
  - Должна быть возможность создания новой игры и подключение к уже существующей
  - Пользователь должен иметь возможность писать свой код и видеть код соперника
  - Пользователь должен иметь возможность отслеживать таймер
  - Пользователь должен иметь возможность отслеживать рейтинг игр
  - Пользователь должен иметь возможность выбора режима игры (по ссылке, с рандомным человеком, с ботом)
  - Пользователь должен иметь возможность выбора уровня сложности
  - Пользователь должен иметь возможность создавать турнир и управлять им
  - Должна быть возможность поддержки разных языков программирования
  - Проверка возможности автодополнения и синтаксической подсветки
  - Проверка обработки некорректного кода
  - Проверка корректности интерпретации и выполнения кода
  - Пользователь должен иметь возможность отправлять и читать сообщения в чате
  - Пользователь должен иметь возможность менять язык задания
  - Настройка светлой/темной темы должна работать корректно
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Страницы должны загружаться не дольше 2–3 секунд (включая мобильные устройства)
  - При высокой нагрузке вместо ошибки 500/503 должна отображаться «очередь» или другое дружелюбное сообщение
  - Все формы должны быть защищены от SQL-инъекций и XSS-атак
  - На разных разрешениях (от 320px до 4K) не должно быть горизонтального скролла
  - Пользователя не должно "выкидывать" из аккаунта при переходе между страницами
  - Сайт должен иметь подробные и чёткие сообщения об ошибках
  - Сайт должен иметь логирование действий
